# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\black\Desktop\PyQt5-Tool-Create\DirectX11Test\Src\Plugin\Module\ParticleEditorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParticleEditor(object):
    def setupUi(self, ParticleEditor):
        ParticleEditor.setObjectName("ParticleEditor")
        ParticleEditor.resize(855, 612)
        self.centralwidget = QtWidgets.QWidget(ParticleEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textureList = QtWidgets.QGroupBox(self.centralwidget)
        self.textureList.setObjectName("textureList")
        self.formLayout_2 = QtWidgets.QFormLayout(self.textureList)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.textureList)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pathView0 = QtWidgets.QLineEdit(self.textureList)
        self.pathView0.setReadOnly(True)
        self.pathView0.setObjectName("pathView0")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.pathView0)
        self.line_11 = QtWidgets.QFrame(self.textureList)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.line_11)
        self.label_34 = QtWidgets.QLabel(self.textureList)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.openTexture1 = QtWidgets.QPushButton(self.textureList)
        self.openTexture1.setObjectName("openTexture1")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.openTexture1)
        self.pathView1 = QtWidgets.QLineEdit(self.textureList)
        self.pathView1.setReadOnly(True)
        self.pathView1.setObjectName("pathView1")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pathView1)
        self.line_12 = QtWidgets.QFrame(self.textureList)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.line_12)
        self.label_28 = QtWidgets.QLabel(self.textureList)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.openTexture2 = QtWidgets.QPushButton(self.textureList)
        self.openTexture2.setObjectName("openTexture2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.openTexture2)
        self.pathView2 = QtWidgets.QLineEdit(self.textureList)
        self.pathView2.setReadOnly(True)
        self.pathView2.setObjectName("pathView2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.pathView2)
        self.line_13 = QtWidgets.QFrame(self.textureList)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.line_13)
        self.label_30 = QtWidgets.QLabel(self.textureList)
        self.label_30.setObjectName("label_30")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.openTexture3 = QtWidgets.QPushButton(self.textureList)
        self.openTexture3.setObjectName("openTexture3")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.openTexture3)
        self.pathView3 = QtWidgets.QLineEdit(self.textureList)
        self.pathView3.setReadOnly(True)
        self.pathView3.setObjectName("pathView3")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.pathView3)
        self.line_14 = QtWidgets.QFrame(self.textureList)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.line_14)
        self.label_35 = QtWidgets.QLabel(self.textureList)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.openTexture4 = QtWidgets.QPushButton(self.textureList)
        self.openTexture4.setObjectName("openTexture4")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.openTexture4)
        self.pathView4 = QtWidgets.QLineEdit(self.textureList)
        self.pathView4.setReadOnly(True)
        self.pathView4.setObjectName("pathView4")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.pathView4)
        self.line_15 = QtWidgets.QFrame(self.textureList)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.line_15)
        self.label_39 = QtWidgets.QLabel(self.textureList)
        self.label_39.setObjectName("label_39")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.openTexture5 = QtWidgets.QPushButton(self.textureList)
        self.openTexture5.setObjectName("openTexture5")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.openTexture5)
        self.pathView5 = QtWidgets.QLineEdit(self.textureList)
        self.pathView5.setReadOnly(True)
        self.pathView5.setObjectName("pathView5")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.pathView5)
        self.line_16 = QtWidgets.QFrame(self.textureList)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.SpanningRole, self.line_16)
        self.label_47 = QtWidgets.QLabel(self.textureList)
        self.label_47.setObjectName("label_47")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.openTexture6 = QtWidgets.QPushButton(self.textureList)
        self.openTexture6.setObjectName("openTexture6")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.openTexture6)
        self.pathView6 = QtWidgets.QLineEdit(self.textureList)
        self.pathView6.setReadOnly(True)
        self.pathView6.setObjectName("pathView6")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.SpanningRole, self.pathView6)
        self.line_17 = QtWidgets.QFrame(self.textureList)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.formLayout_2.setWidget(20, QtWidgets.QFormLayout.SpanningRole, self.line_17)
        self.label_49 = QtWidgets.QLabel(self.textureList)
        self.label_49.setObjectName("label_49")
        self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.openTexture7 = QtWidgets.QPushButton(self.textureList)
        self.openTexture7.setObjectName("openTexture7")
        self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.openTexture7)
        self.pathView7 = QtWidgets.QLineEdit(self.textureList)
        self.pathView7.setReadOnly(True)
        self.pathView7.setObjectName("pathView7")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.SpanningRole, self.pathView7)
        self.openTexture0 = QtWidgets.QPushButton(self.textureList)
        self.openTexture0.setObjectName("openTexture0")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.openTexture0)
        self.gridLayout.addWidget(self.textureList, 0, 0, 2, 1)
        self.instanceList = QtWidgets.QGroupBox(self.centralwidget)
        self.instanceList.setObjectName("instanceList")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.instanceList)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.activeInstance = QtWidgets.QLineEdit(self.instanceList)
        self.activeInstance.setReadOnly(True)
        self.activeInstance.setObjectName("activeInstance")
        self.gridLayout_13.addWidget(self.activeInstance, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.instanceList)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.instanceList)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 0, 0, 1, 1)
        self.instanceListWidget = InstanceList(self.instanceList)
        self.instanceListWidget.setObjectName("instanceListWidget")
        self.gridLayout_13.addWidget(self.instanceListWidget, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.instanceList, 0, 1, 2, 1)
        self.generateParameters = QtWidgets.QGroupBox(self.centralwidget)
        self.generateParameters.setObjectName("generateParameters")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.generateParameters)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_31 = QtWidgets.QLabel(self.generateParameters)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_14.addWidget(self.label_31, 0, 0, 1, 1)
        self.spinSectionTime = QtWidgets.QDoubleSpinBox(self.generateParameters)
        self.spinSectionTime.setMaximum(1000.0)
        self.spinSectionTime.setSingleStep(0.1)
        self.spinSectionTime.setObjectName("spinSectionTime")
        self.gridLayout_14.addWidget(self.spinSectionTime, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.generateParameters)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_14.addWidget(self.label_14, 1, 0, 1, 1)
        self.spinGenerateFrame = QtWidgets.QSpinBox(self.generateParameters)
        self.spinGenerateFrame.setObjectName("spinGenerateFrame")
        self.gridLayout_14.addWidget(self.spinGenerateFrame, 0, 1, 1, 1)
        self.random = QtWidgets.QGroupBox(self.generateParameters)
        self.random.setObjectName("random")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.random)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.random)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_8.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.random)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 7, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.random)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.spinRandColorRed = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.spinRandColorRed.setMaximum(1.0)
        self.spinRandColorRed.setSingleStep(0.1)
        self.spinRandColorRed.setObjectName("spinRandColorRed")
        self.gridLayout_11.addWidget(self.spinRandColorRed, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_11)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 1)
        self.spinRandColorGreen = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.spinRandColorGreen.setMaximum(1.0)
        self.spinRandColorGreen.setSingleStep(0.1)
        self.spinRandColorGreen.setObjectName("spinRandColorGreen")
        self.gridLayout_11.addWidget(self.spinRandColorGreen, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_11)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 0, 2, 1, 1)
        self.spinRandColorBlue = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.spinRandColorBlue.setMaximum(1.0)
        self.spinRandColorBlue.setSingleStep(0.1)
        self.spinRandColorBlue.setObjectName("spinRandColorBlue")
        self.gridLayout_11.addWidget(self.spinRandColorBlue, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_11, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.random)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 0, 4, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 0, 2, 1, 1)
        self.spinRandPosX = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinRandPosX.setMinimum(0.0)
        self.spinRandPosX.setMaximum(1000.0)
        self.spinRandPosX.setObjectName("spinRandPosX")
        self.gridLayout_2.addWidget(self.spinRandPosX, 0, 1, 1, 1)
        self.spinRandPosY = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinRandPosY.setMinimum(0.0)
        self.spinRandPosY.setMaximum(1000.0)
        self.spinRandPosY.setObjectName("spinRandPosY")
        self.gridLayout_2.addWidget(self.spinRandPosY, 0, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 0, 0, 1, 1)
        self.spinRandPosZ = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinRandPosZ.setMinimum(0.0)
        self.spinRandPosZ.setMaximum(1000.0)
        self.spinRandPosZ.setObjectName("spinRandPosZ")
        self.gridLayout_2.addWidget(self.spinRandPosZ, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.random)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_43 = QtWidgets.QLabel(self.groupBox_10)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_10.addWidget(self.label_43, 0, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_10)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_10.addWidget(self.label_44, 0, 2, 1, 1)
        self.spinRandPowerY = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.spinRandPowerY.setMinimum(0.0)
        self.spinRandPowerY.setMaximum(1000.0)
        self.spinRandPowerY.setObjectName("spinRandPowerY")
        self.gridLayout_10.addWidget(self.spinRandPowerY, 0, 3, 1, 1)
        self.spinRandPowerX = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.spinRandPowerX.setMinimum(0.0)
        self.spinRandPowerX.setMaximum(1000.0)
        self.spinRandPowerX.setObjectName("spinRandPowerX")
        self.gridLayout_10.addWidget(self.spinRandPowerX, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_10)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_10.addWidget(self.label_45, 0, 4, 1, 1)
        self.spinRandPowerZ = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.spinRandPowerZ.setMinimum(0.0)
        self.spinRandPowerZ.setMaximum(1000.0)
        self.spinRandPowerZ.setObjectName("spinRandPowerZ")
        self.gridLayout_10.addWidget(self.spinRandPowerZ, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_10, 2, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.random)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.spinRandMoveX = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.spinRandMoveX.setMinimum(0.0)
        self.spinRandMoveX.setMaximum(1000.0)
        self.spinRandMoveX.setObjectName("spinRandMoveX")
        self.gridLayout_9.addWidget(self.spinRandMoveX, 0, 1, 1, 1)
        self.spinRandMoveY = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.spinRandMoveY.setMinimum(0.0)
        self.spinRandMoveY.setMaximum(1000.0)
        self.spinRandMoveY.setObjectName("spinRandMoveY")
        self.gridLayout_9.addWidget(self.spinRandMoveY, 0, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_8)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_9.addWidget(self.label_41, 0, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_8)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_9.addWidget(self.label_42, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_8)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_9.addWidget(self.label_50, 0, 0, 1, 1)
        self.spinRandMoveZ = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.spinRandMoveZ.setMinimum(0.0)
        self.spinRandMoveZ.setMaximum(1000.0)
        self.spinRandMoveZ.setObjectName("spinRandMoveZ")
        self.gridLayout_9.addWidget(self.spinRandMoveZ, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.random)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_8.addWidget(self.pushButton_3, 6, 0, 1, 1)
        self.gridLayout_14.addWidget(self.random, 5, 0, 1, 2)
        self.blendMode = QtWidgets.QGroupBox(self.generateParameters)
        self.blendMode.setObjectName("blendMode")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.blendMode)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.blendCopy = QtWidgets.QRadioButton(self.blendMode)
        self.blendCopy.setChecked(True)
        self.blendCopy.setObjectName("blendCopy")
        self.horizontalLayout.addWidget(self.blendCopy)
        self.blendAdd = QtWidgets.QRadioButton(self.blendMode)
        self.blendAdd.setObjectName("blendAdd")
        self.horizontalLayout.addWidget(self.blendAdd)
        self.blendSub = QtWidgets.QRadioButton(self.blendMode)
        self.blendSub.setObjectName("blendSub")
        self.horizontalLayout.addWidget(self.blendSub)
        self.blendScreen = QtWidgets.QRadioButton(self.blendMode)
        self.blendScreen.setObjectName("blendScreen")
        self.horizontalLayout.addWidget(self.blendScreen)
        self.gridLayout_14.addWidget(self.blendMode, 3, 0, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.generateParameters)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_14.addWidget(self.label_29, 2, 0, 1, 1)
        self.spinPlayTime = QtWidgets.QDoubleSpinBox(self.generateParameters)
        self.spinPlayTime.setMinimum(-1.0)
        self.spinPlayTime.setObjectName("spinPlayTime")
        self.gridLayout_14.addWidget(self.spinPlayTime, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.generateParameters, 0, 3, 2, 1)
        self.particleParameters = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.particleParameters.setFont(font)
        self.particleParameters.setObjectName("particleParameters")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.particleParameters)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_26 = QtWidgets.QLabel(self.particleParameters)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 18, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.particleParameters)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 13, 1, 1, 1)
        self.spinTextureIndex = QtWidgets.QSpinBox(self.particleParameters)
        self.spinTextureIndex.setMinimum(-1)
        self.spinTextureIndex.setMaximum(7)
        self.spinTextureIndex.setProperty("value", -1)
        self.spinTextureIndex.setObjectName("spinTextureIndex")
        self.gridLayout_12.addWidget(self.spinTextureIndex, 16, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.particleParameters)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_12.addWidget(self.label_24, 11, 1, 1, 1)
        self.spinStartScale = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinStartScale.setSingleStep(0.1)
        self.spinStartScale.setObjectName("spinStartScale")
        self.gridLayout_12.addWidget(self.spinStartScale, 11, 2, 1, 1)
        self.spinEndScale = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinEndScale.setSingleStep(0.1)
        self.spinEndScale.setObjectName("spinEndScale")
        self.gridLayout_12.addWidget(self.spinEndScale, 13, 2, 1, 1)
        self.spinAliveTime = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinAliveTime.setSingleStep(0.1)
        self.spinAliveTime.setObjectName("spinAliveTime")
        self.gridLayout_12.addWidget(self.spinAliveTime, 5, 2, 1, 1)
        self.spinFadeInTime = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinFadeInTime.setSingleStep(0.1)
        self.spinFadeInTime.setObjectName("spinFadeInTime")
        self.gridLayout_12.addWidget(self.spinFadeInTime, 7, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.particleParameters)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 5, 1, 1, 1)
        self.spinFadeOutTime = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinFadeOutTime.setSingleStep(0.1)
        self.spinFadeOutTime.setObjectName("spinFadeOutTime")
        self.gridLayout_12.addWidget(self.spinFadeOutTime, 9, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.particleParameters)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.particleParameters)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 16, 1, 1, 1)
        self.colorPickerButton = QtWidgets.QPushButton(self.particleParameters)
        self.colorPickerButton.setObjectName("colorPickerButton")
        self.gridLayout_12.addWidget(self.colorPickerButton, 18, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.particleParameters)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 9, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 4, 1, 1)
        self.spinPosY = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinPosY.setMinimum(-1000.0)
        self.spinPosY.setMaximum(1000.0)
        self.spinPosY.setObjectName("spinPosY")
        self.gridLayout_3.addWidget(self.spinPosY, 0, 3, 1, 1)
        self.spinPosZ = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinPosZ.setMinimum(-1000.0)
        self.spinPosZ.setMaximum(1000.0)
        self.spinPosZ.setObjectName("spinPosZ")
        self.gridLayout_3.addWidget(self.spinPosZ, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.spinPosX = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinPosX.setMinimum(-1000.0)
        self.spinPosX.setMaximum(1000.0)
        self.spinPosX.setObjectName("spinPosX")
        self.gridLayout_3.addWidget(self.spinPosX, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 0, 1, 1, 2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 1, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 1, 0, 1, 1)
        self.spinUVSizeX = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.spinUVSizeX.setMinimum(0.0)
        self.spinUVSizeX.setMaximum(1.0)
        self.spinUVSizeX.setSingleStep(0.1)
        self.spinUVSizeX.setObjectName("spinUVSizeX")
        self.gridLayout_7.addWidget(self.spinUVSizeX, 1, 1, 1, 1)
        self.spinUVSizeY = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.spinUVSizeY.setMinimum(0.0)
        self.spinUVSizeY.setMaximum(1.0)
        self.spinUVSizeY.setSingleStep(0.1)
        self.spinUVSizeY.setObjectName("spinUVSizeY")
        self.gridLayout_7.addWidget(self.spinUVSizeY, 1, 3, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_7, 4, 1, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 2, 1, 1)
        self.spinUVPosX = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.spinUVPosX.setMinimum(0.0)
        self.spinUVPosX.setMaximum(1.0)
        self.spinUVPosX.setSingleStep(0.1)
        self.spinUVPosX.setObjectName("spinUVPosX")
        self.gridLayout_6.addWidget(self.spinUVPosX, 0, 1, 1, 1)
        self.spinUVPosY = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.spinUVPosY.setMinimum(0.0)
        self.spinUVPosY.setMaximum(1.0)
        self.spinUVPosY.setSingleStep(0.1)
        self.spinUVPosY.setObjectName("spinUVPosY")
        self.gridLayout_6.addWidget(self.spinUVPosY, 0, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_6, 3, 1, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinPowerZ = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinPowerZ.setMinimum(-1000.0)
        self.spinPowerZ.setMaximum(1000.0)
        self.spinPowerZ.setObjectName("spinPowerZ")
        self.gridLayout_5.addWidget(self.spinPowerZ, 0, 5, 1, 1)
        self.spinPowerY = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinPowerY.setMinimum(-1000.0)
        self.spinPowerY.setMaximum(1000.0)
        self.spinPowerY.setObjectName("spinPowerY")
        self.gridLayout_5.addWidget(self.spinPowerY, 0, 3, 1, 1)
        self.spinPowerX = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinPowerX.setMinimum(-1000.0)
        self.spinPowerX.setMaximum(1000.0)
        self.spinPowerX.setObjectName("spinPowerX")
        self.gridLayout_5.addWidget(self.spinPowerX, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 2, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_5, 2, 1, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinMoveY = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinMoveY.setMinimum(-1000.0)
        self.spinMoveY.setMaximum(1000.0)
        self.spinMoveY.setObjectName("spinMoveY")
        self.gridLayout_4.addWidget(self.spinMoveY, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 2, 1, 1)
        self.spinMoveX = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinMoveX.setMinimum(-1000.0)
        self.spinMoveX.setMaximum(1000.0)
        self.spinMoveX.setObjectName("spinMoveX")
        self.gridLayout_4.addWidget(self.spinMoveX, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinMoveZ = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinMoveZ.setMinimum(-1000.0)
        self.spinMoveZ.setMaximum(1000.0)
        self.spinMoveZ.setObjectName("spinMoveZ")
        self.gridLayout_4.addWidget(self.spinMoveZ, 0, 5, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_4, 1, 1, 1, 2)
        self.label_32 = QtWidgets.QLabel(self.particleParameters)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 14, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.particleParameters)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 15, 1, 1, 1)
        self.spinStartRad = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinStartRad.setObjectName("spinStartRad")
        self.gridLayout_12.addWidget(self.spinStartRad, 14, 2, 1, 1)
        self.spinEndRad = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinEndRad.setObjectName("spinEndRad")
        self.gridLayout_12.addWidget(self.spinEndRad, 15, 2, 1, 1)
        self.gridLayout.addWidget(self.particleParameters, 0, 4, 2, 1)
        ParticleEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ParticleEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menubar.setObjectName("menubar")
        ParticleEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ParticleEditor)
        self.statusbar.setObjectName("statusbar")
        ParticleEditor.setStatusBar(self.statusbar)

        self.retranslateUi(ParticleEditor)
        QtCore.QMetaObject.connectSlotsByName(ParticleEditor)
        ParticleEditor.setTabOrder(self.openTexture0, self.pathView0)
        ParticleEditor.setTabOrder(self.pathView0, self.openTexture1)
        ParticleEditor.setTabOrder(self.openTexture1, self.pathView1)
        ParticleEditor.setTabOrder(self.pathView1, self.openTexture2)
        ParticleEditor.setTabOrder(self.openTexture2, self.pathView2)
        ParticleEditor.setTabOrder(self.pathView2, self.openTexture3)
        ParticleEditor.setTabOrder(self.openTexture3, self.pathView3)
        ParticleEditor.setTabOrder(self.pathView3, self.openTexture4)
        ParticleEditor.setTabOrder(self.openTexture4, self.pathView4)
        ParticleEditor.setTabOrder(self.pathView4, self.openTexture5)
        ParticleEditor.setTabOrder(self.openTexture5, self.pathView5)
        ParticleEditor.setTabOrder(self.pathView5, self.openTexture6)
        ParticleEditor.setTabOrder(self.openTexture6, self.pathView6)
        ParticleEditor.setTabOrder(self.pathView6, self.openTexture7)
        ParticleEditor.setTabOrder(self.openTexture7, self.pathView7)
        ParticleEditor.setTabOrder(self.pathView7, self.activeInstance)
        ParticleEditor.setTabOrder(self.activeInstance, self.instanceListWidget)
        ParticleEditor.setTabOrder(self.instanceListWidget, self.spinGenerateFrame)
        ParticleEditor.setTabOrder(self.spinGenerateFrame, self.spinSectionTime)
        ParticleEditor.setTabOrder(self.spinSectionTime, self.spinPlayTime)
        ParticleEditor.setTabOrder(self.spinPlayTime, self.blendCopy)
        ParticleEditor.setTabOrder(self.blendCopy, self.blendAdd)
        ParticleEditor.setTabOrder(self.blendAdd, self.blendSub)
        ParticleEditor.setTabOrder(self.blendSub, self.blendScreen)
        ParticleEditor.setTabOrder(self.blendScreen, self.spinRandPosX)
        ParticleEditor.setTabOrder(self.spinRandPosX, self.spinRandPosY)
        ParticleEditor.setTabOrder(self.spinRandPosY, self.spinRandPosZ)
        ParticleEditor.setTabOrder(self.spinRandPosZ, self.spinRandMoveX)
        ParticleEditor.setTabOrder(self.spinRandMoveX, self.spinRandMoveY)
        ParticleEditor.setTabOrder(self.spinRandMoveY, self.spinRandMoveZ)
        ParticleEditor.setTabOrder(self.spinRandMoveZ, self.spinRandPowerX)
        ParticleEditor.setTabOrder(self.spinRandPowerX, self.spinRandPowerY)
        ParticleEditor.setTabOrder(self.spinRandPowerY, self.spinRandPowerZ)
        ParticleEditor.setTabOrder(self.spinRandPowerZ, self.spinRandColorRed)
        ParticleEditor.setTabOrder(self.spinRandColorRed, self.spinRandColorGreen)
        ParticleEditor.setTabOrder(self.spinRandColorGreen, self.spinRandColorBlue)
        ParticleEditor.setTabOrder(self.spinRandColorBlue, self.pushButton)
        ParticleEditor.setTabOrder(self.pushButton, self.pushButton_2)
        ParticleEditor.setTabOrder(self.pushButton_2, self.pushButton_3)
        ParticleEditor.setTabOrder(self.pushButton_3, self.spinPosX)
        ParticleEditor.setTabOrder(self.spinPosX, self.spinPosY)
        ParticleEditor.setTabOrder(self.spinPosY, self.spinPosZ)
        ParticleEditor.setTabOrder(self.spinPosZ, self.spinMoveX)
        ParticleEditor.setTabOrder(self.spinMoveX, self.spinMoveY)
        ParticleEditor.setTabOrder(self.spinMoveY, self.spinMoveZ)
        ParticleEditor.setTabOrder(self.spinMoveZ, self.spinPowerX)
        ParticleEditor.setTabOrder(self.spinPowerX, self.spinPowerY)
        ParticleEditor.setTabOrder(self.spinPowerY, self.spinPowerZ)
        ParticleEditor.setTabOrder(self.spinPowerZ, self.spinUVPosX)
        ParticleEditor.setTabOrder(self.spinUVPosX, self.spinUVPosY)
        ParticleEditor.setTabOrder(self.spinUVPosY, self.spinUVSizeX)
        ParticleEditor.setTabOrder(self.spinUVSizeX, self.spinUVSizeY)
        ParticleEditor.setTabOrder(self.spinUVSizeY, self.spinAliveTime)
        ParticleEditor.setTabOrder(self.spinAliveTime, self.spinFadeInTime)
        ParticleEditor.setTabOrder(self.spinFadeInTime, self.spinFadeOutTime)
        ParticleEditor.setTabOrder(self.spinFadeOutTime, self.spinStartScale)
        ParticleEditor.setTabOrder(self.spinStartScale, self.spinEndScale)
        ParticleEditor.setTabOrder(self.spinEndScale, self.spinStartRad)
        ParticleEditor.setTabOrder(self.spinStartRad, self.spinEndRad)
        ParticleEditor.setTabOrder(self.spinEndRad, self.spinTextureIndex)
        ParticleEditor.setTabOrder(self.spinTextureIndex, self.colorPickerButton)

    def retranslateUi(self, ParticleEditor):
        _translate = QtCore.QCoreApplication.translate
        ParticleEditor.setWindowTitle(_translate("ParticleEditor", "Particle Editor"))
        self.textureList.setTitle(_translate("ParticleEditor", "Texture List"))
        self.label_3.setText(_translate("ParticleEditor", "slot 0"))
        self.label_34.setText(_translate("ParticleEditor", "slot 1"))
        self.openTexture1.setText(_translate("ParticleEditor", "open texture"))
        self.label_28.setText(_translate("ParticleEditor", "slot 2"))
        self.openTexture2.setText(_translate("ParticleEditor", "open texture"))
        self.label_30.setText(_translate("ParticleEditor", "slot 3"))
        self.openTexture3.setText(_translate("ParticleEditor", "open texture"))
        self.label_35.setText(_translate("ParticleEditor", "slot 4"))
        self.openTexture4.setText(_translate("ParticleEditor", "open texture"))
        self.label_39.setText(_translate("ParticleEditor", "slot 5"))
        self.openTexture5.setText(_translate("ParticleEditor", "open texture"))
        self.label_47.setText(_translate("ParticleEditor", "slot 6"))
        self.openTexture6.setText(_translate("ParticleEditor", "open texture"))
        self.label_49.setText(_translate("ParticleEditor", "slot 7"))
        self.openTexture7.setText(_translate("ParticleEditor", "open texture"))
        self.openTexture0.setText(_translate("ParticleEditor", "open texture"))
        self.instanceList.setTitle(_translate("ParticleEditor", "Instance List"))
        self.label_27.setText(_translate("ParticleEditor", "list"))
        self.label_2.setText(_translate("ParticleEditor", "active"))
        self.generateParameters.setTitle(_translate("ParticleEditor", "Generate Parameters"))
        self.label_31.setWhatsThis(_translate("ParticleEditor", "生成時に何個パーティクルを生成するか"))
        self.label_31.setText(_translate("ParticleEditor", "generate count (生成時いくつ生成するか)"))
        self.label_14.setWhatsThis(_translate("ParticleEditor", "パーティクルを何msごとに出現させるかの設定"))
        self.label_14.setText(_translate("ParticleEditor", "section time (何秒ごとに生成するか sec)"))
        self.random.setTitle(_translate("ParticleEditor", "random"))
        self.pushButton_2.setText(_translate("ParticleEditor", "Pause (予約)"))
        self.pushButton.setText(_translate("ParticleEditor", "Play (予約)"))
        self.groupBox_11.setTitle(_translate("ParticleEditor", "color (補正色)"))
        self.label_6.setText(_translate("ParticleEditor", "red"))
        self.label_13.setText(_translate("ParticleEditor", "blue"))
        self.label_12.setText(_translate("ParticleEditor", "green"))
        self.groupBox_2.setTitle(_translate("ParticleEditor", "pos (半径)"))
        self.label_37.setText(_translate("ParticleEditor", "z"))
        self.label_36.setText(_translate("ParticleEditor", "y"))
        self.label_40.setText(_translate("ParticleEditor", "x"))
        self.groupBox_10.setTitle(_translate("ParticleEditor", "power (半径)"))
        self.label_43.setText(_translate("ParticleEditor", "x"))
        self.label_44.setText(_translate("ParticleEditor", "y"))
        self.label_45.setText(_translate("ParticleEditor", "z"))
        self.groupBox_8.setTitle(_translate("ParticleEditor", "move (半径)"))
        self.label_41.setText(_translate("ParticleEditor", "z"))
        self.label_42.setText(_translate("ParticleEditor", "y"))
        self.label_50.setText(_translate("ParticleEditor", "x"))
        self.pushButton_3.setText(_translate("ParticleEditor", "Stop (予約)"))
        self.blendMode.setTitle(_translate("ParticleEditor", "blend mode"))
        self.blendCopy.setText(_translate("ParticleEditor", "copy"))
        self.blendAdd.setText(_translate("ParticleEditor", "add"))
        self.blendSub.setText(_translate("ParticleEditor", "sub"))
        self.blendScreen.setText(_translate("ParticleEditor", "screen"))
        self.label_29.setText(_translate("ParticleEditor", "play time (何秒発生するか -1で無限 sec)"))
        self.particleParameters.setTitle(_translate("ParticleEditor", "Particle Parameters"))
        self.label_26.setWhatsThis(_translate("ParticleEditor", "テクスチャの補正色、テクスチャ無い場合は描画色"))
        self.label_26.setText(_translate("ParticleEditor", "color (補正色)"))
        self.label_25.setWhatsThis(_translate("ParticleEditor", "消滅時のスケール\n"
""))
        self.label_25.setText(_translate("ParticleEditor", "end scale (消滅時のスケール)"))
        self.label_24.setWhatsThis(_translate("ParticleEditor", "生成時のスケール\n"
""))
        self.label_24.setText(_translate("ParticleEditor", "start scale (生成時のスケール)"))
        self.label_21.setWhatsThis(_translate("ParticleEditor", "生存時間"))
        self.label_21.setText(_translate("ParticleEditor", "alive time (生存時間 sec)"))
        self.label_22.setWhatsThis(_translate("ParticleEditor", "フェードインが終わる時間"))
        self.label_22.setText(_translate("ParticleEditor", "fade in time (フェードするまで sec)"))
        self.label_7.setWhatsThis(_translate("ParticleEditor", "テクスチャのスロットの指定、-1でテクスチャ無し"))
        self.label_7.setText(_translate("ParticleEditor", "texture slot (-1でテクスチャ無し)"))
        self.colorPickerButton.setWhatsThis(_translate("ParticleEditor", "カラーピッカーを開きます"))
        self.colorPickerButton.setText(_translate("ParticleEditor", "color picker"))
        self.label_23.setWhatsThis(_translate("ParticleEditor", "フェードアウトが開始される時間\n"
""))
        self.label_23.setText(_translate("ParticleEditor", "fade out time (フェードアウト開始 sec)"))
        self.groupBox_3.setTitle(_translate("ParticleEditor", "pos (位置)"))
        self.label_8.setText(_translate("ParticleEditor", "z"))
        self.label.setText(_translate("ParticleEditor", "y"))
        self.label_18.setText(_translate("ParticleEditor", "x"))
        self.groupBox_7.setTitle(_translate("ParticleEditor", "uv size (UV切り取りサイズ0.0~1.0)"))
        self.label_20.setText(_translate("ParticleEditor", "y"))
        self.label_19.setText(_translate("ParticleEditor", "x"))
        self.groupBox_6.setTitle(_translate("ParticleEditor", "uv pos (UV切り取り位置0.0~1.0)"))
        self.label_17.setText(_translate("ParticleEditor", "y"))
        self.label_16.setText(_translate("ParticleEditor", "x"))
        self.groupBox_5.setTitle(_translate("ParticleEditor", "power (加速度)"))
        self.label_5.setText(_translate("ParticleEditor", "x"))
        self.label_15.setText(_translate("ParticleEditor", "z"))
        self.label_11.setText(_translate("ParticleEditor", "y"))
        self.groupBox_4.setTitle(_translate("ParticleEditor", "move (初速)"))
        self.label_10.setText(_translate("ParticleEditor", "z"))
        self.label_9.setText(_translate("ParticleEditor", "y"))
        self.label_4.setText(_translate("ParticleEditor", "x"))
        self.label_32.setText(_translate("ParticleEditor", "start rad (発生時の角度)"))
        self.label_33.setText(_translate("ParticleEditor", "end rad (消滅時の角度)"))

from Plugin.Module.Instancelist import InstanceList
