# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\black\Desktop\PyQt5-Tool-Create\DirectX11Test\Src\Plugin\Module\ParticleConsole.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1130, 547)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 7, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 3, 1, 1)
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 0, 9, 1, 1)
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 0, 1, 1, 1)
        self.particleParameters = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.particleParameters.setFont(font)
        self.particleParameters.setObjectName("particleParameters")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.particleParameters)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_25 = QtWidgets.QLabel(self.particleParameters)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 13, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 1, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 1, 0, 1, 1)
        self.spinUVSizeX = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.spinUVSizeX.setMinimum(0.0)
        self.spinUVSizeX.setMaximum(1.0)
        self.spinUVSizeX.setObjectName("spinUVSizeX")
        self.gridLayout_7.addWidget(self.spinUVSizeX, 1, 1, 1, 1)
        self.spinUVPosY_2 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.spinUVPosY_2.setMinimum(0.0)
        self.spinUVPosY_2.setMaximum(1.0)
        self.spinUVPosY_2.setObjectName("spinUVPosY_2")
        self.gridLayout_7.addWidget(self.spinUVPosY_2, 1, 3, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_7, 4, 0, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 2, 1, 1)
        self.spinUVPosX = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.spinUVPosX.setMinimum(0.0)
        self.spinUVPosX.setMaximum(1.0)
        self.spinUVPosX.setObjectName("spinUVPosX")
        self.gridLayout_6.addWidget(self.spinUVPosX, 0, 1, 1, 1)
        self.spinUVPosY = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.spinUVPosY.setMinimum(0.0)
        self.spinUVPosY.setMaximum(1.0)
        self.spinUVPosY.setObjectName("spinUVPosY")
        self.gridLayout_6.addWidget(self.spinUVPosY, 0, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_6, 3, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinMoveY = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinMoveY.setMinimum(-1000.0)
        self.spinMoveY.setMaximum(1000.0)
        self.spinMoveY.setObjectName("spinMoveY")
        self.gridLayout_4.addWidget(self.spinMoveY, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 2, 1, 1)
        self.spinMoveX = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinMoveX.setMinimum(-1000.0)
        self.spinMoveX.setMaximum(1000.0)
        self.spinMoveX.setObjectName("spinMoveX")
        self.gridLayout_4.addWidget(self.spinMoveX, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinMoveZ = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinMoveZ.setMinimum(-1000.0)
        self.spinMoveZ.setMaximum(1000.0)
        self.spinMoveZ.setObjectName("spinMoveZ")
        self.gridLayout_4.addWidget(self.spinMoveZ, 0, 5, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_4, 1, 0, 1, 2)
        self.spinAliveTime = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinAliveTime.setObjectName("spinAliveTime")
        self.gridLayout_12.addWidget(self.spinAliveTime, 5, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinPowerZ = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinPowerZ.setMinimum(-1000.0)
        self.spinPowerZ.setMaximum(1000.0)
        self.spinPowerZ.setObjectName("spinPowerZ")
        self.gridLayout_5.addWidget(self.spinPowerZ, 0, 5, 1, 1)
        self.spinPowerY = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinPowerY.setMinimum(-1000.0)
        self.spinPowerY.setMaximum(1000.0)
        self.spinPowerY.setObjectName("spinPowerY")
        self.gridLayout_5.addWidget(self.spinPowerY, 0, 3, 1, 1)
        self.spinPowerX = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinPowerX.setMinimum(-1000.0)
        self.spinPowerX.setMaximum(1000.0)
        self.spinPowerX.setObjectName("spinPowerX")
        self.gridLayout_5.addWidget(self.spinPowerX, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 2, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_5, 2, 0, 1, 2)
        self.spinFadeOutTime = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinFadeOutTime.setObjectName("spinFadeOutTime")
        self.gridLayout_12.addWidget(self.spinFadeOutTime, 9, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.particleParameters)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 17, 0, 1, 1)
        self.spinFadeInTime = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinFadeInTime.setObjectName("spinFadeInTime")
        self.gridLayout_12.addWidget(self.spinFadeInTime, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.particleParameters)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_12.addWidget(self.label_5, 15, 0, 1, 1)
        self.colorPickerButton = QtWidgets.QPushButton(self.particleParameters)
        self.colorPickerButton.setObjectName("colorPickerButton")
        self.gridLayout_12.addWidget(self.colorPickerButton, 17, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.particleParameters)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.particleParameters)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.particleParameters)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 9, 0, 1, 1)
        self.spinTextureIndex = QtWidgets.QSpinBox(self.particleParameters)
        self.spinTextureIndex.setMinimum(-1)
        self.spinTextureIndex.setMaximum(7)
        self.spinTextureIndex.setProperty("value", -1)
        self.spinTextureIndex.setObjectName("spinTextureIndex")
        self.gridLayout_12.addWidget(self.spinTextureIndex, 15, 1, 1, 1)
        self.spinStartScale = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinStartScale.setObjectName("spinStartScale")
        self.gridLayout_12.addWidget(self.spinStartScale, 11, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.particleParameters)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_12.addWidget(self.label_24, 11, 0, 1, 1)
        self.spinEndScale = QtWidgets.QDoubleSpinBox(self.particleParameters)
        self.spinEndScale.setObjectName("spinEndScale")
        self.gridLayout_12.addWidget(self.spinEndScale, 13, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.particleParameters)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 4, 1, 1)
        self.spinPosY = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinPosY.setMinimum(-1000.0)
        self.spinPosY.setMaximum(1000.0)
        self.spinPosY.setObjectName("spinPosY")
        self.gridLayout_3.addWidget(self.spinPosY, 0, 3, 1, 1)
        self.spinPosZ = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinPosZ.setMinimum(-1000.0)
        self.spinPosZ.setMaximum(1000.0)
        self.spinPosZ.setObjectName("spinPosZ")
        self.gridLayout_3.addWidget(self.spinPosZ, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinPosX = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinPosX.setMinimum(-1000.0)
        self.spinPosX.setMaximum(1000.0)
        self.spinPosX.setObjectName("spinPosX")
        self.gridLayout_3.addWidget(self.spinPosX, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.particleParameters, 0, 8, 1, 1)
        self.instanceList = QtWidgets.QGroupBox(Form)
        self.instanceList.setObjectName("instanceList")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.instanceList)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_10 = QtWidgets.QPushButton(self.instanceList)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_13.addWidget(self.pushButton_10, 1, 0, 1, 1)
        self.instanceListWidget = InstanceList(self.instanceList)
        self.instanceListWidget.setObjectName("instanceListWidget")
        self.gridLayout_13.addWidget(self.instanceListWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.instanceList, 0, 2, 1, 1)
        self.generateParameters = QtWidgets.QGroupBox(Form)
        self.generateParameters.setObjectName("generateParameters")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.generateParameters)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.spinSectionTime = QtWidgets.QDoubleSpinBox(self.generateParameters)
        self.spinSectionTime.setObjectName("spinSectionTime")
        self.gridLayout_14.addWidget(self.spinSectionTime, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.generateParameters)
        self.label_14.setObjectName("label_14")
        self.gridLayout_14.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.generateParameters)
        self.label_31.setObjectName("label_31")
        self.gridLayout_14.addWidget(self.label_31, 0, 0, 1, 1)
        self.spinGenerateFrame = QtWidgets.QSpinBox(self.generateParameters)
        self.spinGenerateFrame.setObjectName("spinGenerateFrame")
        self.gridLayout_14.addWidget(self.spinGenerateFrame, 0, 1, 1, 1)
        self.random = QtWidgets.QGroupBox(self.generateParameters)
        self.random.setObjectName("random")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.random)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.random)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 0, 4, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 0, 2, 1, 1)
        self.spinRandPosX = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinRandPosX.setMinimum(-1000.0)
        self.spinRandPosX.setMaximum(1000.0)
        self.spinRandPosX.setObjectName("spinRandPosX")
        self.gridLayout_2.addWidget(self.spinRandPosX, 0, 1, 1, 1)
        self.spinRandPosY = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinRandPosY.setMinimum(-1000.0)
        self.spinRandPosY.setMaximum(1000.0)
        self.spinRandPosY.setObjectName("spinRandPosY")
        self.gridLayout_2.addWidget(self.spinRandPosY, 0, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 0, 0, 1, 1)
        self.spinRandPosZ = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinRandPosZ.setMinimum(-1000.0)
        self.spinRandPosZ.setMaximum(1000.0)
        self.spinRandPosZ.setObjectName("spinRandPosZ")
        self.gridLayout_2.addWidget(self.spinRandPosZ, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.random)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_43 = QtWidgets.QLabel(self.groupBox_10)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_10.addWidget(self.label_43, 0, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_10)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_10.addWidget(self.label_44, 0, 2, 1, 1)
        self.spinRandPowerY = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.spinRandPowerY.setMinimum(-1000.0)
        self.spinRandPowerY.setMaximum(1000.0)
        self.spinRandPowerY.setObjectName("spinRandPowerY")
        self.gridLayout_10.addWidget(self.spinRandPowerY, 0, 3, 1, 1)
        self.spinRandPowerX = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.spinRandPowerX.setMinimum(-1000.0)
        self.spinRandPowerX.setMaximum(1000.0)
        self.spinRandPowerX.setObjectName("spinRandPowerX")
        self.gridLayout_10.addWidget(self.spinRandPowerX, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_10)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_10.addWidget(self.label_45, 0, 4, 1, 1)
        self.spinRandPowerZ = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.spinRandPowerZ.setMinimum(-1000.0)
        self.spinRandPowerZ.setMaximum(1000.0)
        self.spinRandPowerZ.setObjectName("spinRandPowerZ")
        self.gridLayout_10.addWidget(self.spinRandPowerZ, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_10, 2, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.random)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.spinRandMoveX = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.spinRandMoveX.setMinimum(-1000.0)
        self.spinRandMoveX.setMaximum(1000.0)
        self.spinRandMoveX.setObjectName("spinRandMoveX")
        self.gridLayout_9.addWidget(self.spinRandMoveX, 0, 1, 1, 1)
        self.spinRandMoveY = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.spinRandMoveY.setMinimum(-1000.0)
        self.spinRandMoveY.setMaximum(1000.0)
        self.spinRandMoveY.setObjectName("spinRandMoveY")
        self.gridLayout_9.addWidget(self.spinRandMoveY, 0, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_8)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_9.addWidget(self.label_41, 0, 4, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_8)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 0, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_8)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 0, 0, 1, 1)
        self.spinRandMoveZ = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.spinRandMoveZ.setMinimum(-1000.0)
        self.spinRandMoveZ.setMaximum(1000.0)
        self.spinRandMoveZ.setObjectName("spinRandMoveZ")
        self.gridLayout_9.addWidget(self.spinRandMoveZ, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.random)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.spinRandColorRed = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.spinRandColorRed.setMaximum(1.0)
        self.spinRandColorRed.setObjectName("spinRandColorRed")
        self.gridLayout_11.addWidget(self.spinRandColorRed, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_11)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 1)
        self.spinRandColorGreen = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.spinRandColorGreen.setMaximum(1.0)
        self.spinRandColorGreen.setObjectName("spinRandColorGreen")
        self.gridLayout_11.addWidget(self.spinRandColorGreen, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_11)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 0, 2, 1, 1)
        self.spinRandColorBlue = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.spinRandColorBlue.setMaximum(1.0)
        self.spinRandColorBlue.setObjectName("spinRandColorBlue")
        self.gridLayout_11.addWidget(self.spinRandColorBlue, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_11, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout_14.addWidget(self.random, 4, 0, 1, 2)
        self.blendMode_2 = QtWidgets.QGroupBox(self.generateParameters)
        self.blendMode_2.setObjectName("blendMode_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.blendMode_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.blendCopy = QtWidgets.QRadioButton(self.blendMode_2)
        self.blendCopy.setChecked(True)
        self.blendCopy.setObjectName("blendCopy")
        self.blendMode = QtWidgets.QButtonGroup(Form)
        self.blendMode.setObjectName("blendMode")
        self.blendMode.addButton(self.blendCopy)
        self.horizontalLayout.addWidget(self.blendCopy)
        self.blendAdd = QtWidgets.QRadioButton(self.blendMode_2)
        self.blendAdd.setObjectName("blendAdd")
        self.blendMode.addButton(self.blendAdd)
        self.horizontalLayout.addWidget(self.blendAdd)
        self.blendSub = QtWidgets.QRadioButton(self.blendMode_2)
        self.blendSub.setObjectName("blendSub")
        self.blendMode.addButton(self.blendSub)
        self.horizontalLayout.addWidget(self.blendSub)
        self.blendScreen = QtWidgets.QRadioButton(self.blendMode_2)
        self.blendScreen.setObjectName("blendScreen")
        self.blendMode.addButton(self.blendScreen)
        self.horizontalLayout.addWidget(self.blendScreen)
        self.gridLayout_14.addWidget(self.blendMode_2, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.generateParameters, 0, 6, 1, 1)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 5, 1, 1)
        self.textureList = QtWidgets.QGroupBox(Form)
        self.textureList.setObjectName("textureList")
        self.formLayout = QtWidgets.QFormLayout(self.textureList)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.textureList)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.openTexture0 = QtWidgets.QPushButton(self.textureList)
        self.openTexture0.setObjectName("openTexture0")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.openTexture0)
        self.pathView0 = QtWidgets.QLineEdit(self.textureList)
        self.pathView0.setReadOnly(True)
        self.pathView0.setObjectName("pathView0")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.pathView0)
        self.line_4 = QtWidgets.QFrame(self.textureList)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.line_4)
        self.label_32 = QtWidgets.QLabel(self.textureList)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.openTexture1 = QtWidgets.QPushButton(self.textureList)
        self.openTexture1.setObjectName("openTexture1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.openTexture1)
        self.pathView1 = QtWidgets.QLineEdit(self.textureList)
        self.pathView1.setReadOnly(True)
        self.pathView1.setObjectName("pathView1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pathView1)
        self.line_5 = QtWidgets.QFrame(self.textureList)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.line_5)
        self.label_27 = QtWidgets.QLabel(self.textureList)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.openTexture2 = QtWidgets.QPushButton(self.textureList)
        self.openTexture2.setObjectName("openTexture2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.openTexture2)
        self.pathView2 = QtWidgets.QLineEdit(self.textureList)
        self.pathView2.setReadOnly(True)
        self.pathView2.setObjectName("pathView2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.pathView2)
        self.line_6 = QtWidgets.QFrame(self.textureList)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.line_6)
        self.label_29 = QtWidgets.QLabel(self.textureList)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.openTexture3 = QtWidgets.QPushButton(self.textureList)
        self.openTexture3.setObjectName("openTexture3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.openTexture3)
        self.pathView3 = QtWidgets.QLineEdit(self.textureList)
        self.pathView3.setReadOnly(True)
        self.pathView3.setObjectName("pathView3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.pathView3)
        self.line_7 = QtWidgets.QFrame(self.textureList)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.line_7)
        self.label_33 = QtWidgets.QLabel(self.textureList)
        self.label_33.setObjectName("label_33")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.openTexture4 = QtWidgets.QPushButton(self.textureList)
        self.openTexture4.setObjectName("openTexture4")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.openTexture4)
        self.pathView4 = QtWidgets.QLineEdit(self.textureList)
        self.pathView4.setReadOnly(True)
        self.pathView4.setObjectName("pathView4")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.pathView4)
        self.line_8 = QtWidgets.QFrame(self.textureList)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.line_8)
        self.label_38 = QtWidgets.QLabel(self.textureList)
        self.label_38.setObjectName("label_38")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.openTexture5 = QtWidgets.QPushButton(self.textureList)
        self.openTexture5.setObjectName("openTexture5")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.openTexture5)
        self.pathView5 = QtWidgets.QLineEdit(self.textureList)
        self.pathView5.setReadOnly(True)
        self.pathView5.setObjectName("pathView5")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.pathView5)
        self.line_9 = QtWidgets.QFrame(self.textureList)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.SpanningRole, self.line_9)
        self.label_46 = QtWidgets.QLabel(self.textureList)
        self.label_46.setObjectName("label_46")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.openTexture6 = QtWidgets.QPushButton(self.textureList)
        self.openTexture6.setObjectName("openTexture6")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.openTexture6)
        self.pathView6 = QtWidgets.QLineEdit(self.textureList)
        self.pathView6.setReadOnly(True)
        self.pathView6.setObjectName("pathView6")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.SpanningRole, self.pathView6)
        self.line_10 = QtWidgets.QFrame(self.textureList)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.SpanningRole, self.line_10)
        self.label_48 = QtWidgets.QLabel(self.textureList)
        self.label_48.setObjectName("label_48")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.openTexture7 = QtWidgets.QPushButton(self.textureList)
        self.openTexture7.setObjectName("openTexture7")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.openTexture7)
        self.pathView7 = QtWidgets.QLineEdit(self.textureList)
        self.pathView7.setReadOnly(True)
        self.pathView7.setObjectName("pathView7")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.SpanningRole, self.pathView7)
        self.gridLayout.addWidget(self.textureList, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Particle Console"))
        self.particleParameters.setTitle(_translate("Form", "Particle Parameters"))
        self.label_25.setWhatsThis(_translate("Form", "消滅時のスケール\n"
""))
        self.label_25.setText(_translate("Form", "end scale (消滅時のスケール)"))
        self.groupBox_7.setTitle(_translate("Form", "uv size (UV切り取りサイズ0.0~1.0)"))
        self.label_20.setText(_translate("Form", "y"))
        self.label_19.setText(_translate("Form", "x"))
        self.groupBox_6.setTitle(_translate("Form", "uv pos (UV切り取り位置0.0~1.0)"))
        self.label_17.setText(_translate("Form", "y"))
        self.label_16.setText(_translate("Form", "x"))
        self.groupBox_4.setTitle(_translate("Form", "move (初速)"))
        self.label_10.setText(_translate("Form", "z"))
        self.label_9.setText(_translate("Form", "y"))
        self.label_3.setText(_translate("Form", "x"))
        self.groupBox_5.setTitle(_translate("Form", "power (加速度)"))
        self.label_4.setText(_translate("Form", "x"))
        self.label_15.setText(_translate("Form", "z"))
        self.label_11.setText(_translate("Form", "y"))
        self.label_26.setWhatsThis(_translate("Form", "テクスチャの補正色、テクスチャ無い場合は描画色"))
        self.label_26.setText(_translate("Form", "color (補正色)"))
        self.label_5.setWhatsThis(_translate("Form", "テクスチャのスロットの指定、-1でテクスチャ無し"))
        self.label_5.setText(_translate("Form", "texture slot (-1でテクスチャ無し)"))
        self.colorPickerButton.setWhatsThis(_translate("Form", "カラーピッカーを開きます"))
        self.colorPickerButton.setText(_translate("Form", "color picker"))
        self.label_22.setWhatsThis(_translate("Form", "フェードインが終わる時間"))
        self.label_22.setText(_translate("Form", "fade in time (フェードするまで)"))
        self.label_21.setWhatsThis(_translate("Form", "生存時間"))
        self.label_21.setText(_translate("Form", "alive time (生存時間)"))
        self.label_23.setWhatsThis(_translate("Form", "フェードアウトが開始される時間\n"
""))
        self.label_23.setText(_translate("Form", "fade out time (フェードアウト開始)"))
        self.label_24.setWhatsThis(_translate("Form", "生成時のスケール\n"
""))
        self.label_24.setText(_translate("Form", "start scale (生成時のスケール)"))
        self.groupBox_3.setTitle(_translate("Form", "pos (位置)"))
        self.label_8.setText(_translate("Form", "z"))
        self.label.setText(_translate("Form", "y"))
        self.label_7.setText(_translate("Form", "x"))
        self.instanceList.setTitle(_translate("Form", "Instance List"))
        self.pushButton_10.setText(_translate("Form", "save"))
        self.generateParameters.setTitle(_translate("Form", "Generate Parameters"))
        self.label_14.setWhatsThis(_translate("Form", "パーティクルを何msごとに出現させるかの設定"))
        self.label_14.setText(_translate("Form", "section time (何msごとに生成するか)"))
        self.label_31.setWhatsThis(_translate("Form", "生成時に何個パーティクルを生成するか"))
        self.label_31.setText(_translate("Form", "generate count (生成時いくつ生成するか)"))
        self.random.setTitle(_translate("Form", "random"))
        self.groupBox_2.setTitle(_translate("Form", "pos (位置)"))
        self.label_37.setText(_translate("Form", "z"))
        self.label_36.setText(_translate("Form", "y"))
        self.label_35.setText(_translate("Form", "x"))
        self.groupBox_10.setTitle(_translate("Form", "power (加速度)"))
        self.label_43.setText(_translate("Form", "x"))
        self.label_44.setText(_translate("Form", "y"))
        self.label_45.setText(_translate("Form", "z"))
        self.groupBox_8.setTitle(_translate("Form", "move (初速)"))
        self.label_41.setText(_translate("Form", "z"))
        self.label_40.setText(_translate("Form", "y"))
        self.label_39.setText(_translate("Form", "x"))
        self.groupBox_11.setTitle(_translate("Form", "color (補正色)"))
        self.label_6.setText(_translate("Form", "r"))
        self.label_13.setText(_translate("Form", "b"))
        self.label_12.setText(_translate("Form", "g"))
        self.blendMode_2.setTitle(_translate("Form", "blend mode"))
        self.blendCopy.setText(_translate("Form", "copy"))
        self.blendAdd.setText(_translate("Form", "add"))
        self.blendSub.setText(_translate("Form", "sub"))
        self.blendScreen.setText(_translate("Form", "screen"))
        self.textureList.setTitle(_translate("Form", "Texture List"))
        self.label_2.setText(_translate("Form", "slot 0"))
        self.openTexture0.setText(_translate("Form", "open texture"))
        self.label_32.setText(_translate("Form", "slot 1"))
        self.openTexture1.setText(_translate("Form", "open texture"))
        self.label_27.setText(_translate("Form", "slot 2"))
        self.openTexture2.setText(_translate("Form", "open texture"))
        self.label_29.setText(_translate("Form", "slot 3"))
        self.openTexture3.setText(_translate("Form", "open texture"))
        self.label_33.setText(_translate("Form", "slot 4"))
        self.openTexture4.setText(_translate("Form", "open texture"))
        self.label_38.setText(_translate("Form", "slot 5"))
        self.openTexture5.setText(_translate("Form", "open texture"))
        self.label_46.setText(_translate("Form", "slot 6"))
        self.openTexture6.setText(_translate("Form", "open texture"))
        self.label_48.setText(_translate("Form", "slot 7"))
        self.openTexture7.setText(_translate("Form", "open texture"))

from Plugin.Module.instancelist import InstanceList